# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cats' do
  use_frameworks!

  # Pods for cats
  
  pod 'SnapKit', '~> 5.6.0'
  pod 'Kingfisher', '~> 7.0'
end
